Repository hebasto/bitcoin, pull requests merged in 2024-05, with the labels that each got.

#165 cmake: Add `docs` build target
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/Doxyfile.in
  doc/developer-notes.md
Labels: enhancement

#172 cmake: Amend `bitcoin_crypto` static library
  src/crypto/CMakeLists.txt
Labels: blocker

#171 cmake: Amend `crc32c` static library
  cmake/crc32c.cmake
Labels: blocker

#174 cmake, doc: Update `depends/README.md`
  depends/README.md
  depends/funcs.mk
Labels: documentation

#169 cmake: Switch from tri-state options to boolean. Stage FOUR
  .github/workflows/cmake.yml
  CMakeLists.txt
  CMakePresets.json
  cmake/introspection.cmake
  cmake/module/FindBerkeleyDB.cmake
  cmake/optional.cmake
  cmake/optional_qt.cmake
Labels: enhancement

#162 cmake: Switch from tri-state options to boolean. Stage TWO
  CMakeLists.txt
  cmake/bitcoin-config.h.in
  cmake/module/FindUSDT.cmake
  cmake/optional.cmake
  depends/Makefile
  depends/toolchain.cmake.in
  src/CMakeLists.txt
  src/util/trace.h
  src/wallet/CMakeLists.txt
Labels: enhancement

#181 cmake: Port PR29904 from the master branch
  src/CMakeLists.txt
  src/test/CMakeLists.txt
  src/util/CMakeLists.txt
Labels: port from autotools

#190 cmake, doc: Modernize cmake invocations
  doc/build-freebsd.md
  doc/build-osx.md
  doc/build-windows-msvc.md
Labels: documentation

#173 cmake: Switch from tri-state options to boolean. Stage FIVE. The GUI
  .github/workflows/cmake.yml
  CMakeLists.txt
  CMakePresets.json
  cmake/module/FindQt5.cmake
  cmake/optional_qt.cmake
  depends/toolchain.cmake.in
  doc/build-freebsd.md
  doc/build-openbsd.md
  doc/build-osx.md
  doc/build-windows-msvc.md
  src/CMakeLists.txt
  src/qt/CMakeLists.txt
Labels: enhancement, documentation

#176 cmake: Add `WITH_DBUS` configuration option
  CMakeLists.txt
  src/qt/CMakeLists.txt
  src/qt/notificator.cpp
  src/qt/notificator.h
Labels: enhancement

#187 cmake: Port PR30031 from the master branch
  src/test/fuzz/CMakeLists.txt
Labels: port from autotools

#188 cmake: Port PR25972 from the master branch
  .github/workflows/cmake.yml
  CMakeLists.txt
Labels: port from autotools

#89 doc: Switch fuzzing docs to CMake
  doc/fuzzing.md
Labels: documentation

#203 cmake: Port PR29494 from the master branch
  src/CMakeLists.txt
Labels: port from autotools

#201 cmake, doc: Update `build-netbsd.md`
  depends/README.md
  doc/build-netbsd.md
Labels: documentation

#207 cmake: Port PR30144 from the master branch
  ci/test/00_setup_env_arm.sh
Labels: port from autotools

#209 cmake, ci: Skip `miniupnpc` package in depends
  .github/workflows/cmake.yml
Labels: tests

#208 cmake, doc: Update `build-unix.md`
  doc/build-unix.md
Labels: documentation

#204 cmake, fuzz, refactor: Improve locality
  src/test/fuzz/CMakeLists.txt
  src/wallet/test/fuzz/CMakeLists.txt
Labels: tests

#206 cmake: Disable `EXPORT_COMPILE_COMMANDS` for all subtree targets
  cmake/crc32c.cmake
  cmake/secp256k1.cmake
Labels: tests

#205 cmake: Fix "tidy" CI job
  ci/test/00_setup_env.sh
  ci/test/03_test_script.sh
Labels: tests

#212 cmake: Port PR28783 from the master branch
  CMakeLists.txt
Labels: port from autotools

#210 [FIXUP] cmake: Rename build option `FUZZ` to `ENABLE_FUZZ`
  ci/test/00_setup_env_native_fuzz.sh
  ci/test/00_setup_env_native_fuzz_with_msan.sh
  ci/test/00_setup_env_native_fuzz_with_valgrind.sh
  doc/fuzzing.md
Labels: bug

#213 cmake: Set Objective C++ `*_INIT` flags in the toolchain file
  .github/workflows/cmake.yml
  depends/toolchain.cmake.in
Labels: bug

#214 cmake: Port PR30137 from the master branch
  CMakeLists.txt
  cmake/module/AddThreadsIfNeeded.cmake
Labels: port from autotools
